configuration: Debug
input_format: profdata
xcodeproj: ProtonMail.xcodeproj
workspace: ProtonMail.xcworkspace
scheme: ProtonMailTests
build_directory: ../test_output
output_directory: ../test_output/slatherOutput
binary_basename: ProtonMail
ignore:
  - ../test_output/SourcePackages/*
